### ISSUE TITLE
[BUG] lazymc incorrectly disabled due to incorrect CPU Arch

### ISSUE THREAD

**Issue by spider-one** [Okazakee/mcserver-lazymc-docker#19]
## Description
Starting a new server results in lazymc being disabled due to incorrect CPU Architecture (reporting as x64 when it should be x86_64 or vice versa?)

Server starts up fine otherwise

## Error shown
Warning! Your CPU architecture (x64) is not supported by Lazymc. Disabling it... 

## Docker Compose
```
services:
  mcserver-lazymc-docker:
    image: okazakee/mcserver-lazymc-docker:latest
    ports:
      - "24565:25565" # change port for multiple instances
    container_name: minecraft-server
    restart: on-failure
    environment:
      SERVER_PROVIDER: fabric
      LAZYMC_VERSION: latest
      MC_VERSION: latest
      SERVER_BUILD: latest
      MC_RAM: 4G
      JAVA_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"
    volumes:
      - "./fabric-001:/mcserver"
```
